import gateManifest from './gate-manifest.json';
import gateUiStatus from './gate-ui-status.json';
import {
  FileCheck,
  Database,
  Shield,
  Package,
  Lock,
  TestTube,
  ScanLine,
  Zap,
  Eye,
  Target,
  TrendingUp,
  Trophy,
  Scale,
  Network,
  FileInput,
  Layers,
  AlertCircle,
  type LucideIcon,
} from 'lucide-react';

export interface ReleaseGateDefinition {
  id: string;
  number: number;
  name: string;
  description: string;
  category: string;
  evidencePath?: string;
  command?: string;
}

export interface ReleaseGateUiEntry extends ReleaseGateDefinition {
  status: 'pass' | 'fail' | 'warning' | 'pending';
  message: string;
  evidence: string[];
  icon: LucideIcon;
  link?: string;
}

const GATE_ICONS: Record<string, LucideIcon> = {
  'gate-1': FileCheck,
  'gate-2': Database,
  'gate-3': Shield,
  'gate-4': Package,
  'gate-5': Lock,
  'gate-6': Shield,
  'gate-7': TestTube,
  'gate-8': ScanLine,
  'gate-9': Zap,
  'gate-10': Eye,
  'gate-11': Target,
  'gate-12': TrendingUp,
  'gate-13': Trophy,
  'gate-14': Scale,
  'gate-15': Network,
  'gate-16': FileInput,
  'gate-17': Layers,
  'gate-18': AlertCircle,
};

const GATE_UI_DETAILS: Record<string, { message: string; evidence: string[]; link?: string }> = {
  'gate-1': {
    message: 'SPEC.md validated — governance terms present',
    link: '/docs/SPEC.md',
    evidence: ['Blueprint, Governance, Release, and Audit language verified in docs/SPEC.md'],
  },
  'gate-2': {
    message: 'REGISTRY.md covers required entities',
    link: '/docs/REGISTRY.md',
    evidence: ['Project, ProjectManifest, GridSettings, Wall, Opening, Material, Environment, Viewport'],
  },
  'gate-3': {
    message: 'Production routes registered in src/routes.tsx',
    evidence: ['/, /spec-center, /registry, /change-requests, /releases, /audit, /world-records'],
  },
  'gate-4': {
    message: 'sample-house-01.json parses successfully',
    evidence: ['Sample JSON object shape validated by release:gates'],
  },
  'gate-5': {
    message: 'vercel.json security headers configured',
    evidence: ['CSP, HSTS, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy'],
  },
  'gate-6': {
    message: 'Firebase variables documented in .env.example',
    evidence: ['VITE_FIREBASE_* keys present in template'],
  },
  'gate-7': {
    message: 'Unit tests pass under pnpm run release:gates:strict',
    evidence: ['Vitest suite — run pnpm run test locally or in CI'],
  },
  'gate-8': {
    message: 'Playwright E2E smoke passes under strict mode',
    evidence: ['Auth gate and private route specs in e2e/'],
  },
  'gate-9': {
    message: 'Save/load evidence attached',
    link: '/docs/release/evidence/save-load-proof.md',
    evidence: ['docs/release/evidence/save-load-proof.md'],
  },
  'gate-10': {
    message: '2D/3D parity evidence attached',
    link: '/docs/release/evidence/2d-3d-parity-proof.md',
    evidence: ['docs/release/evidence/2d-3d-parity-proof.md'],
  },
  'gate-11': {
    message: 'iPad touch audit evidence attached',
    link: '/docs/release/evidence/ipad-touch-audit.md',
    evidence: ['docs/release/evidence/ipad-touch-audit.md'],
  },
  'gate-12': {
    message: 'Performance notes evidence attached',
    link: '/docs/release/evidence/performance-notes.md',
    evidence: ['docs/release/evidence/performance-notes.md'],
  },
  'gate-13': {
    message: 'World record measurement artifact present',
    link: '/world-records',
    evidence: ['docs/world-record/latest-measurement.json generated by pnpm run record:measure'],
  },
  'gate-14': {
    message: 'AU NCC rule pack covers every active jurisdiction rule with citations',
    evidence: ['src/modules/compliance/rulePacks/auNccVol2H1.test.ts', 'node scripts/verify-gates-14-18.mjs --gate=14'],
  },
  'gate-15': {
    message: 'manifestToBuildingGraph parity tests pass',
    evidence: ['src/domain/buildingGraph/manifestAdapter.test.ts', 'node scripts/verify-gates-14-18.mjs --gate=15'],
  },
  'gate-16': {
    message: 'DXF import fixtures (LINE, LWPOLYLINE, layer filter) pass regression',
    evidence: ['src/core/importers/dxfImport.test.ts', 'node scripts/verify-gates-14-18.mjs --gate=16'],
  },
  'gate-17': {
    message: 'Sheet set composer produces title, plan, and elevation page descriptors',
    evidence: ['src/modules/sheetSet/sheetSetComposer.test.ts', 'node scripts/verify-gates-14-18.mjs --gate=17'],
  },
  'gate-18': {
    message: 'Compliance, council, and cost exports include prototype disclaimers',
    evidence: ['src/governance/gates/decisionIntelligenceDisclaimer.test.ts', 'node scripts/verify-gates-14-18.mjs --gate=18'],
  },
};

export const RELEASE_GATE_MANIFEST = gateManifest.gates as ReleaseGateDefinition[];

export const RELEASE_GATE_COUNT = RELEASE_GATE_MANIFEST.length;

export const WORLD_RECORD_GATE_COUNT = RELEASE_GATE_MANIFEST.filter(
  (gate) => gate.category !== 'world-record-excluded',
).length;

/** Gates 1–12 are the primary world-record metric (pre-release compliance gates). */
export const WORLD_RECORD_METRIC_GATE_COUNT = 12;

type GateUiSnapshot = {
  status: ReleaseGateUiEntry['status'];
  message: string;
};

function fallbackGateStatus(_category: string): ReleaseGateUiEntry['status'] {
  return 'pending';
}

export function getReleaseGatesForUi(): ReleaseGateUiEntry[] {
  const snapshots = gateUiStatus.gates as Record<string, GateUiSnapshot>;

  return RELEASE_GATE_MANIFEST.map((gate) => {
    const details = GATE_UI_DETAILS[gate.id] ?? { message: gate.description, evidence: [] };
    const snapshot = snapshots[gate.id];
    const status = snapshot?.status ?? fallbackGateStatus(gate.category);
    const message = snapshot?.message ?? details.message;

    return {
      ...gate,
      status,
      message,
      evidence: details.evidence,
      icon: GATE_ICONS[gate.id] ?? Shield,
      link: details.link ?? gate.evidencePath,
    };
  });
}

export interface BuildVerificationSummary {
  generatedAt: string;
  lint: 'pass' | 'fail' | 'warning' | 'pending';
  tests: 'pass' | 'fail' | 'warning' | 'pending';
  build: 'pass' | 'fail' | 'warning' | 'pending';
  testsPassed: number | null;
  testsTotal: number | null;
  note: string;
}

export function getBuildVerificationSummary(): BuildVerificationSummary {
  const verification = gateUiStatus.verification as BuildVerificationSummary & { note?: string };
  return {
    generatedAt: gateUiStatus.generatedAt,
    lint: verification.lint ?? 'pending',
    tests: verification.tests ?? 'pending',
    build: verification.build ?? 'pending',
    testsPassed: verification.testsPassed ?? null,
    testsTotal: verification.testsTotal ?? null,
    note: verification.note ?? 'Last verified at build time — run pnpm run release:gates:strict for live counts',
  };
}

export async function downloadEvidencePack(): Promise<void> {
  const measurementRes = await fetch('/world-record/latest-measurement.json');
  const measurement = measurementRes.ok ? await measurementRes.json() : null;
  const pack = {
    exportedAt: new Date().toISOString(),
    releaseGates: getReleaseGatesForUi().map(({ id, name, status, message }) => ({ id, name, status, message })),
    buildVerification: getBuildVerificationSummary(),
    worldRecordMeasurement: measurement,
    gateUiSnapshot: gateUiStatus,
  };

  const blob = new Blob([JSON.stringify(pack, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `vishvakarma-evidence-pack-${new Date().toISOString().slice(0, 10)}.json`;
  link.click();
  URL.revokeObjectURL(url);
}
